server:
  port: 8182
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ozaki5025@gmail.com
    passqord: gywneotp@7475
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true